# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell", inline: $script
end

Vagrant::Config.run do |config| 
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
  config.vm.host_name = "sparkhost"

  config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true  
  config.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"

end