# -*- mode: ruby -*-
# vi: set ft=ruby :


$script = <<SCRIPT
echo I am provisioning...
date > /etc/vm_provision_on_timestamp
SCRIPT

Vagrant.configure(2) do |config|
  #Box config stuff
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
  config.vm.host_name = "pythondev"

  #OK this is where some prvisioning happens 
  config.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"

  #Add any port forwarding you might need below like for example 
  #Tomcat Server port forwarding
  #config.vm.forward_port 8080, 18080
end

