# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
Vagrant.configure(2) do |config|    
  config.vm.box = "ubuntu/trusty64" 
  config.vm.provision :shell, path: "Vagrant-Config/bootstrap.sh"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 27017, host: 27017    
  config.vm.synced_folder "data", "/vagrant_data"
end
