# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/trusty64"
    node1.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
    node1.vm.hostname = 'node1'
    

    node1.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"   

    node1.vm.network :private_network, ip: "192.168.56.101"

    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "node1"]
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
    node2.vm.hostname = 'node2'
    

    node2.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"

    node2.vm.network :private_network, ip: "192.168.56.102"

    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "node2"]
    end
  end
end